import{a as g,S as L,i as a}from"./assets/vendor-DqB7j7Ix.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&r(l)}).observe(document,{childList:!0,subtree:!0});function i(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(t){if(t.ep)return;t.ep=!0;const s=i(t);fetch(t.href,s)}})();const v="51359701-f6006c27d1fc3647654901390",b="https://pixabay.com/api/",w=15;async function f(e,o){const i={key:v,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:w};return(await g.get(b,{params:i})).data}let d;function m(e){const o=document.querySelector(".gallery"),i=e.map(r=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${r.largeImageURL}">
            <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}" />
          </a>
        <div class="info">
  <div class="info-item"><b>Likes</b><span>${r.likes}</span></div>
  <div class="info-item"><b>Views</b><span>${r.views}</span></div>
  <div class="info-item"><b>Comments</b><span>${r.comments}</span></div>
  <div class="info-item"><b>Downloads</b><span>${r.downloads}</span></div>
</div>
        </li>`).join("");o.insertAdjacentHTML("beforeend",i),d?d.refresh():d=new L(".gallery a")}function S(){document.querySelector(".gallery").innerHTML=""}function p(){document.getElementById("loader-text").classList.remove("hidden")}function y(){document.getElementById("loader-text").classList.add("hidden")}function q(){var e;(e=document.querySelector(".load-more"))==null||e.classList.remove("hidden")}function h(){var e;(e=document.querySelector(".load-more"))==null||e.classList.add("hidden")}let c="",n=1,u=0;const E=document.querySelector(".load-more"),R=document.querySelector(".form"),x=document.querySelector('input[name="search-text"]');R.addEventListener("submit",async e=>{if(e.preventDefault(),c=x.value.trim(),!c){a.warning({title:"Увага!",message:"Введіть запит для пошуку зображень.",position:"topRight"});return}n=1,S(),h(),p();try{const o=await f(c,n);u=o.totalHits,o.hits.length===0?a.info({message:"Нічого не знайдено за цим запитом.",position:"topRight"}):(m(o.hits),n*15<u&&q())}catch(o){a.error({message:"Помилка при завантаженні зображень!",position:"topRight"}),console.error(o)}finally{y()}});E.addEventListener("click",async()=>{n+=1,p();try{const e=await f(c,n);m(e.hits),n*15>=u&&(h(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(e){a.error({message:"Помилка при підвантаженні зображень!",position:"topRight"}),console.error(e)}finally{y()}});
//# sourceMappingURL=index.js.map
