import{a as w,S as R,i as s}from"./assets/vendor-DqB7j7Ix.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))r(o);new MutationObserver(o=>{for(const i of o)if(i.type==="childList")for(const d of i.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&r(d)}).observe(document,{childList:!0,subtree:!0});function c(o){const i={};return o.integrity&&(i.integrity=o.integrity),o.referrerPolicy&&(i.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?i.credentials="include":o.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function r(o){if(o.ep)return;o.ep=!0;const i=c(o);fetch(o.href,i)}})();const S="51359701-f6006c27d1fc3647654901390",q="https://pixabay.com/api/",E=15;async function f(t,e){const c={key:S,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:E};return(await w.get(q,{params:c})).data}let u;function m(t){const e=document.querySelector(".gallery"),c=t.map(r=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${r.largeImageURL}">
            <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}" />
          </a>
        <div class="info">
  <div class="info-item"><b>Likes</b><span>${r.likes}</span></div>
  <div class="info-item"><b>Views</b><span>${r.views}</span></div>
  <div class="info-item"><b>Comments</b><span>${r.comments}</span></div>
  <div class="info-item"><b>Downloads</b><span>${r.downloads}</span></div>
</div>
        </li>`).join("");e.insertAdjacentHTML("beforeend",c),u?u.refresh():u=new R(".gallery a")}function p(){document.querySelector(".gallery").innerHTML=""}function g(){document.getElementById("loader-text").classList.remove("hidden")}function h(){document.getElementById("loader-text").classList.add("hidden")}function y(){var t;(t=document.querySelector(".load-more"))==null||t.classList.remove("hidden")}function v(){var t;(t=document.querySelector(".load-more"))==null||t.classList.add("hidden")}let n="",a=1,l=0;document.querySelector(".load-more");const L=document.querySelector(".form"),b=document.querySelector('input[name="search-text"]');L.addEventListener("submit",async t=>{if(t.preventDefault(),n=b.value.trim(),!n){s.warning({title:"Увага!",message:"Введіть запит для пошуку зображень.",position:"topRight"});return}a=1,p(),v(),g();try{const e=await f(n,a);l=e.totalHits,e.hits.length===0?s.info({message:"Нічого не знайдено за цим запитом.",position:"topRight"}):(m(e.hits),a*15<l&&y())}catch(e){s.error({message:"Помилка при завантаженні зображень!",position:"topRight"}),console.error(e)}finally{h()}});L.addEventListener("submit",async t=>{if(t.preventDefault(),n=b.value.trim(),!n){s.warning({title:"Увага!",message:"Введіть запит для пошуку зображень.",position:"topRight"});return}a=1,p(),v(),g();try{const e=await f(n,a);l=e.totalHits,e.hits.length===0?s.info({message:"Нічого не знайдено за цим запитом.",position:"topRight"}):(m(e.hits),a*15<l&&y())}catch(e){s.error({message:"Помилка при завантаженні зображень!",position:"topRight"}),console.error(e)}finally{h()}});L.addEventListener("submit",async t=>{if(t.preventDefault(),n=b.value.trim(),!n){s.warning({title:"Увага!",message:"Введіть запит для пошуку зображень.",position:"topRight"});return}a=1,p(),v(),g();try{const e=await f(n,a);l=e.totalHits,e.hits.length===0?s.info({message:"Нічого не знайдено за цим запитом.",position:"topRight"}):(m(e.hits),a*15<l&&y())}catch(e){s.error({message:"Помилка при завантаженні зображень!",position:"topRight"}),console.error(e)}finally{h()}});
//# sourceMappingURL=index.js.map
